chasis_name: NileSR

# modeling
wheel_diameter: 0.200 
wheel_thickness: 0.060 
wheel_base_x: 0.490 
wheel_base_y: 0.370 
chasis_width: 0.5 
chasis_length: 0.738 
chasis_height: 0.140 

# physics
chasis_mass: 40
steer_mass: 1
steer_stiffness: 350
steer_damping: 20
wheel_mass: 2
wheel_damping: 10
wheel_friction: 1